name: Build & Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build JAR
        run: ./mvnw clean package

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }} spring-boot-demo:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }} spring-boot-demo:latest
